export const buyerEvents = [
  {
    id: "live-music-night",
    title: "Live Music Night",
    category: "Music",
    date: "May 25, 2025",
    city: "Tirana",
    venue: "Pallati i Kongreseve",
    price: "EUR 25 - EUR 60",
    tag: "Top Event",
    description: "An unforgettable live concert night with regional artists, light shows, and an energetic crowd.",
    organizerName: "Eventix Live",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "tech-conference-2025",
    title: "Tech Conference 2025",
    category: "Conference",
    date: "May 24, 2025",
    city: "Tirana",
    venue: "Tirana Convention Center",
    price: "EUR 49 - EUR 149",
    tag: "Top Event",
    description: "A full-day technology conference with talks, product demos, and networking sessions.",
    organizerName: "Acme Events",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "stand-up-comedy-night",
    title: "Stand Up Comedy Night",
    category: "Comedy",
    date: "May 30, 2025",
    city: "Prishtina",
    venue: "Arturbina Theater",
    price: "EUR 15 - EUR 25",
    tag: "This Weekend",
    description: "A relaxed comedy night featuring local and regional stand-up performers.",
    organizerName: "Arturbina Events",
    image: "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "food-festival-tirana",
    title: "Food Festival Tirana",
    category: "Festival",
    date: "Jun 1, 2025",
    city: "Tirana",
    venue: "Sheshi Skenderbej",
    price: "Free",
    tag: "Free Event",
    description: "A public food festival with local restaurants, street food, and live music.",
    organizerName: "Tirana Food Collective",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "yoga-in-the-park",
    title: "Yoga in the Park",
    category: "Wellness",
    date: "Jun 5, 2025",
    city: "Prizren",
    venue: "Grand Park",
    price: "EUR 10 - EUR 20",
    tag: "This Weekend",
    description: "Outdoor yoga and wellness sessions for all levels in a calm park setting.",
    organizerName: "Wellness Tirana",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "summer-vibes-party",
    title: "Summer Vibes Party",
    category: "Party",
    date: "Jun 7, 2025",
    city: "Peja",
    venue: "Level Club",
    price: "EUR 20 - EUR 30",
    tag: "Top Event",
    description: "A summer party with DJs, dancing, and late-night entertainment.",
    organizerName: "Level Club",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "sunset-lake-festival",
    title: "Sunset Lake Festival",
    category: "Festival",
    date: "Jun 14, 2025",
    city: "Pogradec",
    venue: "Lake Stage",
    price: "EUR 18 - EUR 35",
    tag: "Top Event",
    description: "An open-air lake festival with sunset performances and food stands.",
    organizerName: "Lake Stage",
    image: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "prishtina-beer-fest",
    title: "Prishtina Beer Fest",
    category: "Festival",
    date: "Jun 20, 2025",
    city: "Prishtina",
    venue: "Youth Palace",
    price: "EUR 12 - EUR 22",
    tag: "This Weekend",
    description: "Craft drinks, food vendors, live bands, and a festival crowd in Prishtina.",
    organizerName: "Prishtina Festivals",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "peja-jazz-festival",
    title: "Peja Jazz Festival",
    category: "Music",
    date: "Jun 28, 2025",
    city: "Peja",
    venue: "Old Bazaar Stage",
    price: "EUR 20 - EUR 40",
    tag: "Top Event",
    description: "Jazz performances from local and international musicians in Peja's old bazaar.",
    organizerName: "Peja Culture Office",
    image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "prizren-film-nights",
    title: "Prizren Film Nights",
    category: "Festival",
    date: "Jul 4, 2025",
    city: "Prizren",
    venue: "Castle Open Air",
    price: "EUR 8 - EUR 16",
    tag: "Free Event",
    description: "Outdoor film screenings and talks in one of Prizren's most scenic locations.",
    organizerName: "Prizren Film Nights",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "tirana-street-art-fest",
    title: "Tirana Street Art Fest",
    category: "Festival",
    date: "Jul 12, 2025",
    city: "Tirana",
    venue: "New Bazaar",
    price: "Free",
    tag: "Free Event",
    description: "Street art, music, live painting, and creative workshops in Tirana.",
    organizerName: "New Bazaar Creative",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=900&q=80",
  },
];

export const buyerTickets = [
  {
    id: "ticket-live-music",
    event: "Live Music Night",
    code: "EVX-LMN-2048",
    date: "May 25, 2025",
    seat: "General Admission",
    status: "Confirmed",
  },
  {
    id: "ticket-tech",
    event: "Tech Conference 2025",
    code: "EVX-TC25-8831",
    date: "May 24, 2025",
    seat: "Section A",
    status: "Confirmed",
  },
];
